#!/bin/bash

# OK

FunRes=$(zenity --title='Herramientas GrX' --text='Modificar Contraseña del usuario: '${USER^^} --forms --add-password='Contraseña Vieja:' --add-password='Contraseña Nueva:' --add-password='Repetir Conraseña:' --separator=Ⅲ)

if [ $? -eq 0 ];then
	CV=$(echo $FunRes | awk -F'Ⅲ' '{print $1}')
	CN1=$(echo $FunRes | awk -F'Ⅲ' '{print $2}')
	CN2=$(echo $FunRes | awk -F'Ⅲ' '{print $3}')
	if [ ${#CV} -gt 5 ] && [ ${#CN1} -gt 5 ] && [ ${#CN2} -gt 5 ];then
		if [ "$CN1" == "$CN2" ];then
			if [ "$CV" != "$CN1" ];then
				echo $CV |grep -E '[a-z]'|grep -E '[A-Z]'|grep -qE '[0-9]'
				if [ $? -eq 0 ];then
					echo $CN1 |grep -E '[a-z]'|grep -E '[A-Z]'|grep -qE '[0-9]'
					if [ $? -eq 0 ];then
						FunRes=$((echo  "$CV" ; echo  "$CN1" ;)|wbinfo --change-user-password=$USER 2>&1)
							if [ $? -eq 0 ];then
								FunRes=$((echo  "$CV" ; echo  "$CN1" ; echo  "$CN1" ;)| ecryptfs-rewrap-passphrase $HOME/.ecryptfs/wrapped-passphrase 2>&1)
								if [ $? -eq 0 ];then
									FunRes='\nOK'
								else
									FunRes+='\nFALLO'
								fi
							else
								FunRes+='\nFALLO'
							fi						
					else
					FunRes='La nueva contraseña debe contener MAYUSCULAS, minusculas y numeros.'
				fi
				else
					FunRes='La contraseña debe contener MAYUSCULAS, minusculas y numeros.'
				fi
			else
				FunRes='La contraseña nueva no puede ser igual que la anterior.'
			fi
		else
			FunRes='La nueva contraseña no coincide.'
		fi
	else
		FunRes='No ha rellenado todos los campos o la contraseña es demasiado corta.\nMinimo seis caracteres.'
	fi
fi
if [ ${#FunRes} -gt 4 ];then
	zenity --title='Error en la operacion' --error --text="$FunRes"
else
	zenity --title='Error en la operacion' --info --text="Algo no ha ido bien"
fi

